

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: devops_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
