name: CI/CD Portfolio

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1️⃣ Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 2️⃣ Build & Push Frontend Image
      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops-frontend:latest
          file: ./frontend/Dockerfile

      # 3️⃣ Déploiement local (directement sur le runner)
      - name: Deploy application locally
        run: |
          echo "=== 🚀 Déploiement local en cours ==="
          cd ~/DevOps/devops-portfolio
          docker compose pull
          docker compose up -d --force-recreate
          echo "✅ Déploiement terminé avec succès !"
