name: CI/CD Portfolio

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # -------------------------------
      # 0️⃣ Récupération du code source
      # -------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------------
      # 1️⃣ Connexion à Docker Hub
      # -------------------------------
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # -------------------------------
      # 2️⃣ Build & Push de l’image frontend
      # -------------------------------
      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/devops-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/devops-frontend:${{ github.run_number }}
          file: ./frontend/Dockerfile

      # -------------------------------
      # 3️⃣ Déploiement sur ton serveur distant via SSH
      # -------------------------------
      - name: Deploy to remote server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/devops-portfolio
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker compose pull
            docker compose up -d --force-recreate
            docker image prune -f
